import {ERC20_ABI} from "./ERC20_ABI";
import {NORD_RAMP_FACET_ABI} from "./NORD_RAMP_FACET_ABI";
import {NORD_GETTERS_FACET_ABI} from "./NORD_GETTERS_FACET_ABI";

export default {ERC20_ABI, NORD_RAMP_FACET_ABI, NORD_GETTERS_FACET: NORD_GETTERS_FACET_ABI};
